FROM tensorflow/magenta

VOLUME /data

RUN apt-get update
RUN apt-get install -y \
    vim \
    tmux \
    screen \
    git \
    curl

# python packages
RUN pip install --upgrade pip
RUN pip install \
    jupyter_contrib_nbextensions

RUN jupyter contrib nbextension install --user

# ENTRYPOINT ["/bin/bash"]
